version: '3.9'
services:
  apache:
    image: httpd:latest
    container_name: my-apache-app
    volumes:
    - ./legacy_old:/usr/local/apache2/htdocs
    networks:
      - proxy

networks:
  proxy:
    external: true
