import type { ITheme } from "@xterm/xterm";

export const terminalPalette = {
  background: "#282828",
  pageBackground: "#1d2021",
  foreground: "#ebdbb2",
  muted: "#928374",
  red: "#cc241d",
  green: "#98971a",
  yellow: "#d79921",
  blue: "#458588",
  magenta: "#b16286",
  cyan: "#689d6a",
  orange: "#fe8019",
  window: "#3c3836",
  border: "#504945",
  brightGreen: "#b8bb26",
  brightYellow: "#fabd2f",
  brightBlue: "#83a598",
  brightMagenta: "#d3869b",
  brightCyan: "#8ec07c",
} as const;

export const terminalTheme: ITheme = {
  background: terminalPalette.background,
  foreground: terminalPalette.foreground,
  cursor: terminalPalette.foreground,
  black: terminalPalette.background,
  red: terminalPalette.red,
  green: terminalPalette.green,
  yellow: terminalPalette.yellow,
  blue: terminalPalette.blue,
  magenta: terminalPalette.magenta,
  cyan: terminalPalette.cyan,
  white: "#a89984",
  brightBlack: terminalPalette.muted,
  brightRed: "#fb4934",
  brightGreen: terminalPalette.brightGreen,
  brightYellow: terminalPalette.brightYellow,
  brightBlue: terminalPalette.brightBlue,
  brightMagenta: terminalPalette.brightMagenta,
  brightCyan: terminalPalette.brightCyan,
  brightWhite: terminalPalette.foreground,
};
